### ISSUE TITLE
large files > 4gb corrupt the possibility to clone the repos, also from command line "git xet clone"

### ISSUE THREAD

**Issue by Oozaruu** [xetdata/xet-tools#21]
**Describe the bug**
large files > 4gb corrupt the possibility to clone the repos, also from command line "git xet clone"

**Frequency**
persistent

**Steps to reproduce**
To reproduce the behavior:
1. push on your repos a large file >4gb
2. try to clone repos
3. See error

**Expected behavior**
i want to clone repository, but i can't

**Screenshots**

**Environment**
 - Internet connection: [e.g., wired fiber, VPN, wireless coffee shop]
 - Device: [e.g., iPhone X, MacBook]
 - OS: [e.g., Debian 11.2, macOS 12.2]
 - Browser: [e.g. Chrome, Safari]
 - CLI version: [`xetcmd -V` output]

**Additional context**

**Comment by erinys** [comment]
Hi @Oozaruu, thanks for the bug report! We tried to reproduce this with the client but were unable to. 

Could you help us debug by adding some more details about the client, or adding me @erinys to your XetHub repo so that I can see what you're experiencing? I'd be more than happy to hop on a call to help debug as well.

**Comment by erinys** [comment]
Our suspicion is that this bug was caused by pushing large files to a XetHub repository without having git-xet properly managing the repository. 

We have added a check to the client that catches if a file larger than 1MiB is being pushed to our server without git-xet filtering; if so, it will warn the user to check that git-xet is installed.
